version: "3.7"

services:
  # nestjs:
  #   container_name: nestjs
  #   build:
  #     context: ../
  #     dockerfile: ./game-management-docker/Dockerfile-back
  #     target: development
  #   volumes:
  #     - ${APP_BACK_DIRECTORY}:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - ${BACK_SERVER_PORT}:${BACK_SERVER_PORT}
  #     - 9229:9229
  #   command: yarn run start:dev
  #   # command: sleep infinity
  #   env_file:
  #     - .env
  #   networks:
  #     - nestjs-network
  #   depends_on:
  #     - redis
  #     - postgres
  # redis:
  #   container_name: redis-nestjs
  #   image: redis:5
  #   networks:
  #     - nestjs-network
  react:
    container_name: react
    hostname: react
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-front
      target: development
    volumes:
      - ${APP_FRONT_DIRECTORY}:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${FRONT_SERVER_PORT}:${FRONT_SERVER_PORT}
    # command: npm run dev
    command: sleep infinity
    # env_file:
    #   - .env
  # postgres:
  #   container_name: postgres-nestjs
  #   image: postgres:12
  #   networks:
  #     - nestjs-network
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_DB: ${DB_DATABASE_NAME}
  #     PG_DATA: /var/lib/postgresql/data
  #   ports:
  #     - ${DB_PORT}:5432
  #   volumes:
  #     - ${DB_DIRETORY}:/var/lib/postgresql/data
# networks:
#   nestjs-network:
