FROM node:16.13.2 As development

WORKDIR /usr/src/app

COPY ./game-management/package*.json ./

RUN npm install -g @nestjs/cli

RUN yarn install 

COPY ./game-management/. .

# RUN yarn run build

FROM node:16.13.2 as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY ./game-management/package*.json ./

RUN yarn install --only=production

COPY ./game-management/.  .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]